name: prohealth
description: "Prohealth Application"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: any
  persistent_bottom_nav_bar: any
  font_awesome_flutter: any
  lottie: any
  dio: any
  shared_preferences: any
  mailer: any
  provider: any
  flutter_svg: any
  flutter_svg_provider: any
  flex_color_picker: any
  file_picker: any
  intl: any
  path_provider: ^2.0.9
  shimmer: any
  js: ^0.6.4
  open_file: any
  amplify_flutter: any
  amplify_storage_s3: any
  flutter_aws_s3_client: ^0.6.0
  #http: ^0.13.3
  http: any
  aws_s3_upload: any
  amplify_core: ^2.5.0
  crypto: ^3.0.0
  amplify_auth_cognito: ^2.5.0
  permission_handler: ^11.3.1
  flutter_dotenv: ^5.0.2
  flutter_html: ^3.0.0-beta.2
  flutter_typeahead: ^5.2.0
  url_launcher: ^6.3.0
  app_links: ^6.1.4
  signature: ^5.0.0
  country_picker: ^2.0.26
  csc_picker: ^0.2.7
  modal_progress_hud_nsn: ^0.5.0
  image_picker_web: ^4.0.0
  webview_flutter: ^4.8.0
  image_picker: ^1.1.2
  printing: any
  pdf: ^3.11.0
  universal_io: any
  encrypt: any
  cached_network_image: any
  google_maps_flutter: ^2.9.0
  google_maps_flutter_web: ^0.5.10
  geocoding: ^3.0.0
  auto_size_text: any
  calendar_view: ^1.2.0
  fl_chart: ^0.70.1
  mime: ^2.0.0
  flutter_masked_text2: ^0.9.1
  intl_phone_number_input: any
  intl_phone_field: ^3.0.0
  mask_text_input_formatter: ^2.9.0
  html: any
  geolocator: any
  google_geocoding_api: any
  flutter_widget_from_html: ^0.15.2
  flutter_pdfview: ^1.3.3
  dropdown_button2: any
  flutter_html_to_pdf: any
  syncfusion_flutter_charts: ^27.2.2
  syncfusion_flutter_gauges: ^27.2.2
  flutter_rating_stars: any
  dotted_border: any
  mapbox_maps_flutter: any
  open_file_macos: ^0.0.1



#  riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/hr_dashboard/
    - images/em_dashboard/
    - images/sm/
    - images/oasis_emr/
    - images/sm/sm_dashboard/
    - images/mobile_images/
    - images/error/
    - images/tab_images/
    - web/icons/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Fira_Sans
      fonts:

               - asset: images/fonts/FiraSans_Bold.ttf
               - asset: images/fonts/FiraSans_italic.ttf
               - asset: images/fonts/FiraSans_Medium.ttf
               - asset: images/fonts/FiraSans_Regular.ttf
               - asset: images/fonts/FiraSans_SemiBold.ttf
               - asset: images/fonts/FiraSans-Black.ttf
               - asset: images/fonts/FiraSans-BlackItalic.ttf
               - asset: images/fonts/FiraSans-ExtraBold.ttf
               - asset: images/fonts/FiraSans-ExtraBoldItalic.ttf
               - asset: images/fonts/FiraSans-ExtraLight.ttf
               - asset: images/fonts/FiraSans-ExtraLightItalic.ttf
               - asset: images/fonts/FiraSans-Light.ttf
               - asset: images/fonts/FiraSans-LightItalic.ttf
               - asset: images/fonts/FiraSans-MediumItalic.ttf
               - asset: images/fonts/FiraSans-SemiBoldItalic.ttf
               - asset: images/fonts/FiraSans-Thin.ttf
               - asset: images/fonts/FiraSans-ThinItalic.ttf



#                   - asset: assets/fonts/Fira_Sans/FiraSans-Black.ttf
#                   - asset: assets/fonts/Fira_Sans/FiraSans-BlackItalic.ttf
#                   - asset: assets/fonts/Fira_Sans/FiraSans-Bold.ttf
#                   - asset: assets/fonts/Fira_Sans/FiraSans-BoldItalic.ttf
#                   - asset: assets/fonts/Fira_Sans/FiraSans-ExtraBold.ttf
#                   - asset: assets/fonts/Fira_Sans/FiraSans-ExtraBoldItalic.ttf
#                   - asset: assets/fonts/Fira_Sans/FiraSans-ExtraLight.ttf
#                   - asset: assets/fonts/Fira_Sans/FiraSans-ExtraLightItalic.ttf
#                   - asset: assets/fonts/Fira_Sans/FiraSans-Italic.ttf
#                   - asset: assets/fonts/Fira_Sans/FiraSans-Light.ttf
#                   - asset: assets/fonts/Fira_Sans/FiraSans-LightItalic.ttf
#                   - asset: assets/fonts/Fira_Sans/FiraSans-Medium.ttf
#                   - asset: assets/fonts/Fira_Sans/FiraSans-MediumItalic.ttf
#                   - asset: assets/fonts/Fira_Sans/FiraSans-Regular.ttf
#                   - asset: assets/fonts/Fira_Sans/FiraSans-SemiBold.ttf
#                   - asset: assets/fonts/Fira_Sans/FiraSans-SemiBoldItalic.ttf
#                   - asset: assets/fonts/Fira_Sans/FiraSans-Thin.ttf
#                   - asset: assets/fonts/Fira_Sans/FiraSans-ThinItalic.ttf
#                   - asset: assets/fonts/Fira_Sans/OFL.txt

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
